### ISSUE TITLE
matrix test account

### ISSUE THREAD

**Issue by strukturart** [farooqkz/matrix-client#2]
a matrix test account would be helpful during the development phase. In the login area the input fields would already be pre-filled.

**Comment by farooqkz** [comment]
Are you suggesting that for development I create a test matrix account and pre-fill Login fields with them?

**Comment by strukturart** [comment]
yes

**Comment by farooqkz** [comment]
That could be used to spam rooms and other people...

**Comment by farooqkz** [comment]
it doesn't matter during what phase, someone could abuse.
